mv ../debs/libnvinfer* ../dockers/nvinfer/
mv ../debs/python3-libnvinfer* ../dockers/nvinfer/
mv ../debs/tensorrt* ../dockers/tensorrt/
mv ../debs/graphsurgeon* ../dockers/tensorrt/
mv ../debs/uff-converter* ../dockers/tensorrt/
mv ../debs/libcudnn* ../dockers/cudnn/
mv ../debs/cuda*.zip ../dockers/opencv/
mv ../debs/cuda*.patch ../dockers/opencv/
mv ../debs/cuda* ../dockers/cuda/
mv ../debs/Jetson* ../dockers/l4t/